services:
  - redis
  - postgresql
  - docker
language: python
jobs:
  include:
  - python: "2.7"
    env: TOX_ENV=py27-sentry821
  - python: "2.7"
    env: TOX_ENV=py27-sentry822
  - python: "2.7"
    env: TOX_ENV=py27-sentry9
  - python: "2.7"
    env: TOX_ENV=py27-sentry91
  - python: "3.7"
    env: TOX_ENV=py37-sentry20
install:
  - sudo apt update
  - sudo apt install libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config -y
  - docker run -p 8123:8123 -p 9000:9000 -p 9009:9009 -d --name sentry_clickhouse yandex/clickhouse-server:20.3.9.70 
  - docker run -p 1218:1218 -d -e CLICKHOUSE_HOST=127.0.0.1:9000 getsentry/snuba:nightly 
  - docker ps -a
  - travis_retry pip install tox
before_script:
  - psql -c 'create database sentry;' -U postgres
script: tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: vortland
  password:
    secure: b2Uk7+6JmsSDiE9q7Jx5SA/fu2Zf3AC9dvu3vJNhLPlCU1CqVry7b8acbjByYzwatOWa2K7PnmKzO/Og7GDdSeHeAj3zzHpFAWCENV7sX8c5Vx2Ac4W3RZ1ZnKkmBJKLAJft6FZwwrGIhjGUtiArNcbLalnKBGpG5ywPYqdGrl1sAmveuuxmALsTOkGQuSzK03Knv3qck3QizuDWmqOUYknRgPItPo1P21/TvoBme57stkb9PJbavS4UtbW34SBc6MMgSUjpAkqDqzbNv/M3hZR/QswZ1G5TGNeU40gqseDSDii/j69fmsrtL41WQkk43GhwX/1KyxdtZXnAdQQyBJALB78kuEGb1MCoBTSW5LtgFusdGXnkScpYRo7YVE9PGZ0r4bqaUap/yx0nyFxaNwipvbFPrfEbE3y9InDeCWO/89kGMJefglbz7ymN42y394QtXdoEeF84uMHwqDHZYwpz3ZWtCGgdl9GejauWYJVjCDlCLmeCgJqkcF4RG5V0pcojfJbb0rE1/bKwz5FgdetGM1SWjxCeKu++3wB0Q18QX0rpLDefBQ07jZhgJ1yKL0Os18UCP3JONNHV1ua2gPK7E5uG1wxr+sBg989bCRefXNFZmynqFPda94rVbVzpEbEJ1tIFHoo1qXfAOS0hVbrVsbaunymxm9/r07bf4n4=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  distributions: sdist bdist_wheel
