services:
  - redis-server
language: python
python:
  - "2.7"
install:
  - travis_retry pip install tox
script: tox -e $TOX_ENV
env:
  - TOX_ENV=py27-sentry821
  - TOX_ENV=py27-sentry822
  - TOX_ENV=py27-sentry9
after_success:
  - bash <(curl -s https://codecov.io/bash)
