services:
  - redis
  - postgresql
  - docker
language: python
jobs:
  include:
  - python: "3.7"
    env: TOX_ENV=py37-sentry20
install:
  - sudo apt update
  - sudo apt install libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config -y
  - docker network create -d bridge sentry_test
  - docker run -p 8123:8123 -p 9000:9000 -p 9009:9009 --network sentry_test -d --name sentry_clickhouse yandex/clickhouse-server:20.3.9.70 
  - docker run -p 1218:1218 -d -e SNUBA_SETTINGS=docker -e DEBUG=1 -e CLICKHOUSE_HOST=sentry_clickhouse --network sentry_test --name sentry_snuba getsentry/snuba:nightly devserver --no-workers
  - docker run --name sentry_zookeeper -p 2181:2181 -d --network sentry_test -e ZOOKEEPER_CLIENT_PORT=2181 confluentinc/cp-zookeeper:4.1.0
  - docker run --name sentry_kafka -d -p 9092:9092 --network sentry_test -e KAFKA_ZOOKEEPER_CONNECT=sentry_zookeeper:2181 -e KAFKA_LISTENERS=INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092 -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://127.0.0.1:9093,EXTERNAL://127.0.0.1:9092 -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 confluentinc/cp-kafka:5.1.2
  - docker ps -a
  - travis_retry pip install tox
before_script:
  - psql -c 'create database sentry;' -U postgres
script: tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: vortland
  password:
    secure: b2Uk7+6JmsSDiE9q7Jx5SA/fu2Zf3AC9dvu3vJNhLPlCU1CqVry7b8acbjByYzwatOWa2K7PnmKzO/Og7GDdSeHeAj3zzHpFAWCENV7sX8c5Vx2Ac4W3RZ1ZnKkmBJKLAJft6FZwwrGIhjGUtiArNcbLalnKBGpG5ywPYqdGrl1sAmveuuxmALsTOkGQuSzK03Knv3qck3QizuDWmqOUYknRgPItPo1P21/TvoBme57stkb9PJbavS4UtbW34SBc6MMgSUjpAkqDqzbNv/M3hZR/QswZ1G5TGNeU40gqseDSDii/j69fmsrtL41WQkk43GhwX/1KyxdtZXnAdQQyBJALB78kuEGb1MCoBTSW5LtgFusdGXnkScpYRo7YVE9PGZ0r4bqaUap/yx0nyFxaNwipvbFPrfEbE3y9InDeCWO/89kGMJefglbz7ymN42y394QtXdoEeF84uMHwqDHZYwpz3ZWtCGgdl9GejauWYJVjCDlCLmeCgJqkcF4RG5V0pcojfJbb0rE1/bKwz5FgdetGM1SWjxCeKu++3wB0Q18QX0rpLDefBQ07jZhgJ1yKL0Os18UCP3JONNHV1ua2gPK7E5uG1wxr+sBg989bCRefXNFZmynqFPda94rVbVzpEbEJ1tIFHoo1qXfAOS0hVbrVsbaunymxm9/r07bf4n4=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  distributions: sdist bdist_wheel
