services:
  - redis-server
language: python
python:
  - "2.7"
install:
  - travis_retry pip install tox
script: tox -e $TOX_ENV
env:
  - TOX_ENV=sentry89
  - TOX_ENV=sentry810
  - TOX_ENV=sentry811
  - TOX_ENV=sentry812
after_success:
  - bash <(curl -s https://codecov.io/bash)